version: '3'

services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      REDIS_URL: "redis://redis:6379/0"  

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
